# Generated by Django 3.2.8 on 2022-04-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='captain_register',
            table='Captain_Register',
        ),
    ]
