# Generated by Django 3.2.8 on 2022-04-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captainapp', '0002_alter_captain_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain_register',
            name='status',
            field=models.CharField(db_column='status', default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
