# Generated by Django 3.2.8 on 2022-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captainapp', '0004_cap_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cap_feedback',
        ),
    ]
