# Generated by Django 3.2.8 on 2022-04-23 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rapido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portor',
            fields=[
                ('rapido_id', models.AutoField(primary_key=True, serialize=False)),
                ('orgine', models.CharField(db_column='orgine', max_length=50, verbose_name='Orgine')),
                ('destination', models.CharField(db_column='destination', max_length=50, verbose_name='Destination')),
                ('distance', models.CharField(db_column='distance', max_length=50, verbose_name='Distance')),
                ('subtotal', models.CharField(db_column='subtotal', max_length=50, verbose_name='Subtotal')),
                ('gst', models.CharField(db_column='gst', max_length=50, verbose_name='Gst')),
                ('total', models.CharField(db_column='total', max_length=50, verbose_name='Total')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Portor',
            },
        ),
    ]
