# Generated by Django 3.2.8 on 2022-04-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_lynk_swiggy_genie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lynk',
            old_name='rapido_id',
            new_name='Lynk_id',
        ),
        migrations.RenameField(
            model_name='portor',
            old_name='rapido_id',
            new_name='Portor_id',
        ),
        migrations.RenameField(
            model_name='swiggy_genie',
            old_name='rapido_id',
            new_name='swiggy_genie_id',
        ),
    ]
