# Generated by Django 3.2.8 on 2022-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20220423_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='lynk',
            name='user_email',
            field=models.EmailField(blank=True, db_column='user_email', default='pending', max_length=100, null=True, verbose_name='User_Email'),
        ),
        migrations.AddField(
            model_name='portor',
            name='user_email',
            field=models.EmailField(blank=True, db_column='user_email', default='pending', max_length=100, null=True, verbose_name='User_Email'),
        ),
        migrations.AddField(
            model_name='rapido',
            name='user_email',
            field=models.EmailField(blank=True, db_column='user_email', default='pending', max_length=100, null=True, verbose_name='User_Email'),
        ),
        migrations.AddField(
            model_name='swiggy_genie',
            name='user_email',
            field=models.EmailField(blank=True, db_column='user_email', default='pending', max_length=100, null=True, verbose_name='User_Email'),
        ),
    ]
