# Generated by Django 3.2.8 on 2022-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20220502_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='portor',
            name='vechile_type',
            field=models.CharField(db_column='vechile_type', max_length=50, null=True, verbose_name='Vechile_type'),
        ),
    ]
