# Generated by Django 3.2.8 on 2022-05-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_lynk_vechile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='user_otp',
            field=models.BigIntegerField(db_column='user_otp', null=True, verbose_name='User_otp'),
        ),
    ]
