# Generated by Django 3.2.8 on 2022-05-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_user_register_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lynk',
            old_name='Lynk_id',
            new_name='a_id',
        ),
        migrations.RenameField(
            model_name='portor',
            old_name='Portor_id',
            new_name='a_id',
        ),
        migrations.RenameField(
            model_name='rapido',
            old_name='rapido_id',
            new_name='a_id',
        ),
        migrations.RenameField(
            model_name='swiggy_genie',
            old_name='swiggy_genie_id',
            new_name='a_id',
        ),
    ]
