# Generated by Django 3.2.8 on 2022-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20220515_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lynk',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='portor',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rapido',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='swiggy_genie',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
