# Generated by Django 3.2.8 on 2022-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20220515_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='lynk',
            name='cap_name',
            field=models.CharField(db_column='cap_name', max_length=50, null=True, verbose_name='Cap_name'),
        ),
        migrations.AddField(
            model_name='portor',
            name='cap_name',
            field=models.CharField(db_column='cap_name', max_length=50, null=True, verbose_name='Cap_name'),
        ),
        migrations.AddField(
            model_name='rapido',
            name='cap_name',
            field=models.CharField(db_column='cap_name', max_length=50, null=True, verbose_name='Cap_name'),
        ),
        migrations.AddField(
            model_name='swiggy_genie',
            name='cap_name',
            field=models.CharField(db_column='cap_name', max_length=50, null=True, verbose_name='Cap_name'),
        ),
    ]
