# Generated by Django 3.2.8 on 2022-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_auto_20220515_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_feedback',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, null=True, verbose_name='Name')),
                ('phone', models.BigIntegerField(db_column='phone', null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100, null=True, verbose_name='Email')),
                ('orgniztion', models.CharField(db_column='orgniztion', max_length=50, verbose_name='Orgniztion')),
                ('description', models.CharField(db_column='description', max_length=50, verbose_name='Description')),
                ('rating', models.BigIntegerField(db_column='rating', null=True, verbose_name='Rating')),
            ],
            options={
                'db_table': 'User_feedback',
            },
        ),
    ]
