# Generated by Django 3.2.8 on 2022-05-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_user_feedback_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_feedback',
            name='email',
        ),
    ]
