# Generated by Django 3.2.8 on 2022-04-22 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Register',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_name', models.CharField(db_column='par_name', max_length=50, verbose_name='Par_Name')),
                ('par_phone', models.BigIntegerField(db_column='par_phone', verbose_name='Par_Phone')),
                ('partner', models.CharField(db_column='partner', max_length=50, verbose_name='Partner')),
                ('city', models.CharField(db_column='city', max_length=50, verbose_name='City')),
                ('par_license', models.CharField(db_column='par_license', max_length=50, verbose_name='Par_license')),
                ('par_email', models.EmailField(blank=True, db_column='par_email', max_length=100, null=True, verbose_name='Par_Email')),
                ('par_pwd', models.CharField(db_column='par_pwd', max_length=100, verbose_name='Par_Password')),
                ('par_image', models.FileField(db_column='par_image', upload_to='Partner/Profile-image/', verbose_name='Par_Image')),
                ('par_lic', models.FileField(db_column='par_lic', upload_to='Partner/Lic-image/', verbose_name='Par_Lic')),
                ('status', models.CharField(db_column='status', default='pending', max_length=50, verbose_name='Status')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Partner_Register',
            },
        ),
    ]
