# Generated by Django 3.2.8 on 2022-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0002_two_wheeler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_feedback',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=50, verbose_name='Description')),
            ],
            options={
                'db_table': 'Partner_feedback',
            },
        ),
        migrations.AlterField(
            model_name='two_wheeler',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='two_wheeler',
            name='price',
            field=models.CharField(db_column='price', max_length=50, verbose_name='Price'),
        ),
    ]
