# Generated by Django 3.2.8 on 2022-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0004_auto_20220502_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner_feedback',
            name='rating',
            field=models.BigIntegerField(db_column='rating', null=True, verbose_name='Rating'),
        ),
    ]
