# Generated by Django 3.2.8 on 2022-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0007_four_wheeler_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lynk_Four_wheeler',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Name')),
                ('price', models.CharField(db_column='price', max_length=50, verbose_name='Price')),
                ('image', models.FileField(db_column='image', default='null', upload_to='demo/', verbose_name='Image')),
            ],
            options={
                'db_table': 'Lynk_Four_wheeler',
            },
        ),
    ]
