# Generated by Django 3.2.8 on 2022-05-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0008_lynk_four_wheeler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner_feedback',
        ),
    ]
